name: model-training
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
        with:
          sudo: false
    
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python train.py
          
          
